Corrected spelling and grammar mistakes
Consensys/gnark pull request #1360
Opened 2024-12-18 11:17 UTC by detrina

I hope my corrections will be helpful and contribute to improving your work. Thank you for your dedication and effort.

2024-12-18 11:18 UTC, detrina commented
@ivokub Could you please review my corrections?

I hope I was able to help in some way. Thank you for your work.

2024-12-20 14:59 UTC, gbotrel requested changes

2024-12-20 14:59 UTC, gbotrel commented on .github/ISSUE_TEMPLATE/bug_report.md
> +<!--- Provide an unambigous set of steps to reproduce this bug. -->
wrong fix.

2025-01-21 11:46 UTC, ivokub commented
Comments not resolved. Closing stale PR.

2025-01-21 11:46 UTC, closed without merging