perf: `PairingCheck` for BN254 and BLS12-381
Consensys/gnark pull request #1365
Opened 2024-12-20 22:00 UTC by yelhousni

# Description

This PR saves the squarings previously needed in `AssertFinalExpIsOne` for `PairingCheck`.
See discussion https://github.com/Consensys/gnark/discussions/1347.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How has this been tested?

`PairingCheck` passes

# How has this been benchmarked?

The PR saves 371,175 scs for BLS12-381 and 238,793 scs for BN254.

# Checklist:

- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I did not modify files generated from templates
- [x] `golangci-lint` does not output errors locally
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2024-12-24 10:35 UTC, shramee approved these changes
Look great to me!
Thanks for the great work! ❤️

2025-01-17 13:58 UTC, ivokub requested changes
Looks good to me. However I think currently there is too much copied implementation. It works, but in the future when we want to target more optimizations/refactors then I'm afraid we could have mismatch between different code paths.

I would try to refactor common parts into separate functions and then use function calls instead. I can have a try at it.

2025-01-17 13:58 UTC, ivokub commented on std/algebra/emulated/sw_bls12381/hints.go
> +func pairingCheckHint(nativeMod *big.Int, nativeInputs, nativeOutputs []*big.Int) error {
This method is essentially very similar to the finalExpHint? It seems the only difference is that in this method we compute the Milller loop result ourselves. I would refactor the common part into a separate function.

2025-01-17 13:58 UTC, ivokub commented on std/algebra/emulated/sw_bn254/hints.go
> +func pairingCheckHint(nativeMod *big.Int, nativeInputs, nativeOutputs []*big.Int) error {
Similarly, can be refactored with finalExpHint

2025-01-17 13:58 UTC, ivokub commented on std/algebra/emulated/sw_bw6761/hints.go
> +func pairingCheckHint(nativeMod *big.Int, nativeInputs, nativeOutputs []*big.Int) error {
Refactor with finalExpHint

2025-01-17 13:58 UTC, ivokub commented on std/algebra/emulated/sw_bls12381/pairing.go
> +	// check input size match
The method seems to be almost fully inlined version of `millerLoopLInes` and `AssertFinalExpIsOne` (with some small differences). I would try to refer to those method directly. For example for `millerLoopLines` we can add boolean that we want to handle first loop iteration separately. Similarly for `AssertFinalExpIsOne`.

I think it is clearer and also more future-proof in case we have some other changes.

2025-01-17 13:58 UTC, ivokub commented on std/algebra/native/sw_bls12377/pairing2.go
> +	PairingCheck(p.api, inP, inQ)
return error

2025-01-17 15:03 UTC, yelhousni commented on std/algebra/emulated/sw_bw6761/hints.go
> +func pairingCheckHint(nativeMod *big.Int, nativeInputs, nativeOutputs []*big.Int) error {
this one is different (different `mInv`), but I'll what I can do

2025-01-17 15:04 UTC, yelhousni commented
> Looks good to me. However I think currently there is too much copied implementation. It works, but in the future when we want to target more optimizations/refactors then I'm afraid we could have mismatch between different code paths.
> 
> I would try to refactor common parts into separate functions and then use function calls instead. I can have a try at it.

Right, I'll try to refactor some bits.

2025-01-20 12:26 UTC, ivokub approved these changes
Thanks! Now imo is a lot more clearer!

2025-01-21 15:25 UTC, merged