Refac/groth16 mpc
Consensys/gnark pull request #1372
Opened 2024-12-25 21:37 UTC by Tabaie

# Description

https://github.com/Consensys/gnark/pull/1297, but using tools from https://github.com/Consensys/gnark-crypto/pull/589.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How has this been tested?

- [ ] Test A
- [ ] Test B

# How has this been benchmarked?

- [ ] Benchmark A, on Macbook pro M1, 32GB RAM
- [ ] Benchmark B, on x86 Intel xxx, 16GB RAM

# Checklist:

- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I did not modify files generated from templates
- [ ] `golangci-lint` does not output errors locally
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2025-01-21 21:34 UTC, gbotrel requested changes
lgtm, minor changes maybe

2025-01-21 21:34 UTC, gbotrel commented on internal/generator/backend/template/zkpschemes/groth16/mpcsetup/utils.go.tmpl
> +	if N >= 2 {
this looks useless; or the start bound of the for loop below should change

2025-01-21 21:34 UTC, gbotrel commented on internal/generator/backend/template/zkpschemes/groth16/mpcsetup/utils.go.tmpl
> +		if !s[i].IsInSubGroup() {
that's not cheap, we don't have a batch subgroup check yet (@yelhousni wanted to add one) but shouldn't we parallelize since we assume the nominal case is everything is in subgroup ?

2025-01-21 21:34 UTC, gbotrel commented on internal/utils/test_utils/test_utils.go
> +func ConditionalLog(v ...any) {
I was going to suggest more idiomatic way to toggle logging levels, but it seems this is not used anyway, remove?

2025-01-21 21:34 UTC, gbotrel commented on internal/utils/slices.go
> +func AppendRefs[T any](s []any, v []T) []any {
is this still needed with golang slices generic stuff ?

2025-01-22 21:28 UTC, Tabaie commented on internal/utils/test_utils/test_utils.go
> +func ConditionalLog(v ...any) {
What is that way? I think it's nice to have a tool lying around even if not used on main

2025-01-22 21:35 UTC, Tabaie commented on internal/utils/slices.go
> +func AppendRefs[T any](s []any, v []T) []any {
Just went through the package docs. Nothing there does it compactly.

2025-01-22 23:59 UTC, ivokub requested changes
Thanks Arya! It looks really nice. Imo I understood it mostly. There are a few comments though, see inline.

A few of the comments are nice to have and you don't need to address now. We could do it in separate PR:
- optional randomness source for contribution
- being able to change hash function for challenge computation for cool tricks a la providing SNARK of ceremony correctness

2025-01-22 23:59 UTC, ivokub commented on backend/groth16/bls12-377/mpcsetup/phase2.go
> +	n := len(commons.G1.AlphaTau)
We already initialized variable `size := len(commons.G1.AlphaTau)`. Could reuse here.

2025-01-22 23:59 UTC, ivokub commented on backend/groth16/bls12-377/mpcsetup/phase2.go
> +func (p *Phase2) hash() []byte {
similarly as for Phase1, should be able to use provided hash function.

2025-01-22 23:59 UTC, ivokub commented on backend/groth16/bn254/mpcsetup/unit_test.go
> +package mpcsetup
File only generated for BN254? I would code-generate just in case.

2025-01-22 23:59 UTC, ivokub commented on backend/groth16/bls12-377/mpcsetup/phase1.go
> +func (p *Phase1) hash() []byte {
And imo, the method could also be public and defined:
```func (p *Phase) Challenge(previous []byte) []byte```

2025-01-22 23:59 UTC, ivokub commented on io/roundtrip.go
> +			if err = equal(from, r); err != nil {
I would keep it as is, imo there may be unwanted side-effects of using `Equal` if exists - there are already a few types in gnark which have the Equal method defined and they may be more strict than needed.

It seems like it is used to avoid comparing `Challenge` field in a test. But at least for me it would be clearer to manually empty the Challenge field manually when needed in the test. This current approach may break imo other roundtrip tests.

2025-01-22 23:59 UTC, ivokub commented on backend/groth16/bls12-377/mpcsetup/phase1.go
> +	next.Challenge = challenge
My assumption was that verification wouldn't change the inputs, but it does as we write `next.Challenge`. This imo may have practical side effects that the contributions are not static (a la when hashing serialized proofs). Instead, I would provide the challenge as argument to `Verify` and then `VerifyPhase1` automatically carries the continuation over to next round (with computing it using `newChallenge := Phase1.Hash(challenge)`)

2025-01-22 23:59 UTC, ivokub commented on backend/groth16/bls12-377/mpcsetup/phase2.go
> +	next.Challenge = challenge
Similarly as for Phase1 imo Phase2.Verify shouldn't change the inputs. See the corresponding comment.

2025-01-23 00:09 UTC, ivokub commented on internal/utils/test_utils/test_utils.go
> +func ConditionalLog(v ...any) {
I'd also remove. Imo having only a single toggle for conditional logger is too wide - imo it would be useful if could toggle individually, e.g. based on environment variable:
```
// ConditionalLog logs v... when environment variable envToggle is defined
func ConditionalLog(envToggle string, v ...any)
```

But I would mainly remove it because it is incompatible with `github.com/consensys/gnark/logger` package. I'd keep a single logging approach so that we would have unified message style etc.

2025-01-23 17:01 UTC, Tabaie commented on backend/groth16/bls12-377/mpcsetup/setup_test.go
>  	assert := require.New(t)
Which methods do you have in mind? Since the setup has to be in a custom way (imitating how an actual multiparty ceremony would go with objects being written to and read from the network) there is only the proof and verification stages to get help with, and those are short enough imo.

2025-01-23 17:04 UTC, Tabaie commented on backend/groth16/bn254/mpcsetup/unit_test.go
> +package mpcsetup
The idea was not to clog the CI with unit tests. The full test is still generated for all curves. Ignoring the unit tests saves 5 seconds per curve on my machine. Perhaps not worth it?

2025-01-23 17:14 UTC, Tabaie commented on backend/groth16/bls12-377/mpcsetup/phase1.go
> +	next.Challenge = challenge
It's only changed if it is empty.

2025-01-23 18:07 UTC, Tabaie commented on backend/groth16/bls12-377/mpcsetup/phase1.go
> +func (p *Phase1) hash() []byte {
Would it perhaps be better to remove the `challenge` field entirely, and just feed it as input to the `Contribute` and `Verify` functions?

2025-01-23 18:09 UTC, Tabaie commented on backend/groth16/bls12-377/mpcsetup/phase1.go
> +func (p *Phase1) hash() []byte {
The downside of this approach is that when sending contributions on the wire the user has to read/write two objects rather than one.

2025-01-24 00:54 UTC, ivokub commented on backend/groth16/bls12-377/mpcsetup/phase1.go
> +func (p *Phase1) hash() []byte {
But in practice do we need to send challenge on the wire? When the user returns contribution to the sequencer, then it doesn't need to send the challenge, sequencer can compute it on its own (and it actually already does it, assuming that it verifies the contributions).

Now, the question imo is if the user is sent the tip of the ceremony for starting their contribution, then should it verify the full state of the current ceremony. Imo for me it would make sense it should, to ensure that it doesn't contribute to some fork etc. From practical point of view, it is probably too heavy for the users to verify and it could only contribute based on current trusted tip (i.e. ceremony tip and running challenge). And imo then it makes sense that challenge is separate, to indicate its optionality. And in this case imo we can provide it separately to `Contribute` and `Verify` 

But its only my gut feeling, maybe it is okay to keep it in, but add comment that it is "trusted" value and should be verfied in full.

2025-01-24 00:59 UTC, ivokub commented on backend/groth16/bn254/mpcsetup/unit_test.go
> +package mpcsetup
In that case, I would still code generate, but maybe conditionally add `test.Skip()` in case the curve isn't BN254. Then atleast we ensure that everything is syntactically correct and the unit test is covered in code generation.

2025-01-24 01:10 UTC, ivokub commented on backend/groth16/bls12-377/mpcsetup/setup_test.go
>  	assert := require.New(t)
There is method below `proveVerifyCircuit`, but indeed it uses fixed proving and verifying key and `test.Assert` doesn't currently have a way to test it like this. But still, `test.Assert` is a very simple wrapper around `require.Assertions`, keeping all the methods what `require.Assertions` has. And imo this unifies the testing style if we use same instance everywhere.

2025-01-24 04:05 UTC, Tabaie commented on backend/groth16/bls12-377/mpcsetup/setup_test.go
>  	assert := require.New(t)
Ah so we generally better not use the testify repo directly?

2025-01-24 10:36 UTC, ivokub commented on backend/groth16/bls12-377/mpcsetup/utils.go
> +	}*/
Indeed - but currently the functions `scaleG1InPlace` and `scaleG2InPlace` are used only in one method in `phase1.go` where we know anyway that `len(tauUpdates) == len(c.G1.Tau)` (etc for AlphaTau and BetaTau).

Even more, now having a second look - I think we could just inline `powers` and `scaleG1InPlace` without defining utility methods at all and avoid too early generefication. Then we can avoid allocating the slices `tauUpdates`, `betaUpdates` and `alphaUpdates`.

2025-01-24 10:43 UTC, ivokub commented on backend/groth16/bls12-377/mpcsetup/setup_test.go
> +func getTestCircuit() *cs.R1CS {
And now, we don't even need to have `getTestCircuit` function separately, we can just remove the current `getTestCircuit` function, rename `onceCircuit` variable to `getTestCircuit` and it works exactly the same.

2025-01-24 10:57 UTC, ivokub commented on backend/groth16/bls12-377/mpcsetup/utils.go
> +	}*/
And in order to make it parallel, we can use `utils.Parallelize` and then within compute `s = f^start` as the starting point and then at every loop multiply s by f and then do a scalar multiplication.

2025-01-27 04:12 UTC, Tabaie commented on backend/groth16/bls12-377/mpcsetup/phase1.go
> +func (p *Phase1) hash() []byte {
> But in practice do we need to send challenge on the wire?

Yes, any new contributor need to receive the challenge used by the last contribution in order to compute its own challenge (so that the channel reflects the entire protocol transcript)
You are right that the field can be omitted when a contribution is being sent back to the sequencer.

I don't think we should require contributors to verify the whole protocol transcript. That goes against two of the protocol's major design goals:
1. Low entry barrier for contributions: I should be able to contribute relatively easily on a small-ish machine in a short amount of time
2. Indefinite run: The protocol is never truly over. We should always be able to enhance our SRS with more contributions, so the number of contributions is not a constant. So especially in light of (1) the verification effort gets prohibitive.

> but add comment that it is "trusted" value

A trusted value from the contributor's perspective you mean? Because the verifier does reconstruct it, in the same way as you described in the first paragraph:
https://github.com/Consensys/gnark/blob/refac/groth16-mpc/backend/groth16/bn254/mpcsetup/phase1.go#L168

2025-01-27 15:07 UTC, ivokub commented on backend/groth16/bls12-377/mpcsetup/phase1.go
> +func (p *Phase1) hash() []byte {
Yep, I think from practical point of view it doesn't make sense for the contributor to verify the whole chain, only the previous contribution on top it builds its contribution. And I guess it is fine to keep `Challenge` field inside the structs, makes easier to serialize and transport.

2025-02-03 18:56 UTC, Tabaie commented
> Thanks Arya! It looks really nice. Imo I understood it mostly. There are a few comments though, see inline.
> 
> A few of the comments are nice to have and you don't need to address now. We could do it in separate PR:
> 
> * optional randomness source for contribution
> * being able to change hash function for challenge computation for cool tricks a la providing SNARK of ceremony correctness

These are great ideas! I made an issue for them.

2025-02-04 16:53 UTC, gbotrel commented on io/roundtrip.go
> +			if err = equal(from, r); err != nil {
ha, on that one I agree with @ivokub ; I previously had a similar snippet, and had some working round trip tests that actually didn't flag an error because the `Equal` function of an object was not correctly updated in a PR. i.e. `reflect.DeepEqual` is a bit more cumbersome but better for non-regression since it checks everything, including new fields, fields that we precompute, etc, that may not even be checked by a "canonical" `Equal`.

2025-02-04 16:58 UTC, gbotrel commented on backend/groth16/bls12-377/mpcsetup/setup_test.go
>  	assert := require.New(t)
I think it's fine to use testify directly here if there is no methods needed from our wrapper; unless we plan to add some extra logic to test or report in a "consistent" manner, but nothing so far

2025-02-05 17:02 UTC, gbotrel approved these changes

2025-02-05 17:13 UTC, Tabaie commented on backend/groth16/bls12-377/mpcsetup/phase1.go
> +func (p *Phase1) Contribute() {
I agree providing randomness sources would be beneficial for debugging purposes, but are there other uses as well? Perhaps something stronger than whatever the go standard library does for production use?

2025-02-05 17:16 UTC, Tabaie commented on backend/groth16/bls12-377/mpcsetup/phase1.go
> +func (c *SrsCommons) setZero(N uint64) {
It's because `tau[i] = tau^i` so when we set `tau=0` we still get `tau[0] = 1`.
In the first case it's needed as well, since only `tau[1:]` are read.

2025-02-05 17:19 UTC, Tabaie commented on backend/groth16/bls12-377/mpcsetup/phase1.go
> +	proofs struct {
My thinking is that because the challenge sometimes doesn't need to be serialized (for example when a contribution is returning to the coordinator) I'd like to give the contributor the option to nullify it. Considering that the saving is only 32-64 bytes in an object of size ~GB maybe the extra complexity isn't worth it?

Generally I thought it'd be good to default to making things private especially since the parameters are the same object type as the final result of Phase 1, so it's best to make it hard for the user to make the mistake of just grabbing the parameters and calling it a day.

2025-02-05 17:20 UTC, Tabaie commented on backend/groth16/bls12-377/mpcsetup/phase1.go
> +	p.proofs.Tau = mpcsetup.UpdateValues(&tauContrib, p.Challenge, 1)
Great idea. Will implement.

2025-02-05 23:27 UTC, Tabaie commented on backend/groth16/bls12-377/mpcsetup/phase1.go
> +	newContribs := mpcsetup.BeaconContributions(p.hash(), []byte("Groth16 MPC Setup - Phase 1"), beaconChallenge, 3)
I think that's unnecessary since it's not used anywhere else

2025-02-05 23:30 UTC, Tabaie commented on backend/groth16/bls12-377/mpcsetup/phase1.go
> +	if !areInSubGroupG1(next.parameters.G1.Tau[2:]) || !areInSubGroupG1(next.parameters.G1.BetaTau[1:]) || !areInSubGroupG1(next.parameters.G1.AlphaTau[1:]) {
I don't think the order matters here. If the subgroup check fails the function would still fail. For readability imo it's better to have the more essential logic further up.

2025-02-05 23:33 UTC, Tabaie commented on backend/groth16/bls12-377/mpcsetup/phase1.go
>  	sha := sha256.New()
Cool idea indeed! Though I think implementation will be nontrivial - we will have to do some "alignment" work since some of the stuff we're hashing have different lengths. Mark it as a TODO?

2025-02-05 23:39 UTC, Tabaie commented on backend/groth16/bls12-377/mpcsetup/phase2.go
> +	scale := func(point any) {
I think the intention was to avoid repeating the -potentially long- reference to the point being scaled. Changing that now :D

2025-02-06 00:13 UTC, Tabaie commented on backend/groth16/bls12-377/mpcsetup/marshal.go
> +	if err := binary.Read(reader, binary.BigEndian, &N); err != nil {
Yes I think that was an error. Deleted serialization functions for `Phase2Evals`.

2025-02-06 00:15 UTC, Tabaie commented on backend/groth16/bls12-377/mpcsetup/phase2.go
> +		if err := next.Sigmas[i].Verify(challenge, 2+byte(i),
Since each sigma gets its own DST I'd prefer to start from 1 to have 255 commitments possible (not that I see that many being used).

2025-02-06 09:47 UTC, ivokub commented on backend/groth16/bls12-377/mpcsetup/phase1.go
>  	sha := sha256.New()
I see you have already created an issue. I'm okay with postponing it (it is still exploratory imo and currently hardcoding hash is good).

Although I'm not a big believer in TODOs inside the implementation - imo usually they stay in the code indefinitely and then we just remove them (the TODO comments) at some point before audit/release etc. Imo GH issues are more explicit.

2025-02-06 09:49 UTC, ivokub commented on backend/groth16/bls12-377/mpcsetup/phase2.go
> +		if err := next.Sigmas[i].Verify(challenge, 2+byte(i),
Agree that it is good to have separate DST for every commitment. I'm proposing to have a constant for the first commitment and then index from this. A la:
```go
const (
    DST_SIGMA_IDX_0 int = 2
)

// ...
if err := next.Sigmas[i].Verify(challenge, DST_SIGMA_IDX_0+byte(sigma_index) // also rename i to `sigma_index`
```

2025-02-06 20:46 UTC, Tabaie commented on backend/groth16/bls12-377/mpcsetup/phase2.go
> +		if err := next.Sigmas[i].Verify(challenge, 2+byte(i),
Ah yes I think that's what we have now.

2025-02-14 14:07 UTC, ivokub commented on backend/groth16/bls12-377/mpcsetup/setup_test.go
> +func (p *Phase2) Equal(o *Phase2) bool {
Is this method needed anymore when the roundtripchecker doesn't call `Equal` method?

2025-02-14 17:18 UTC, Tabaie commented on internal/utils/test_utils/test_utils.go
> +func Range(n int, startingPoints ...int) []int {
It's generally a pretty handy thing. Doesn't hurt to keep it around should it come up again.

2025-02-14 17:30 UTC, Tabaie commented on backend/groth16/bls12-377/mpcsetup/utils.go
> +	return wp.Submit(len(s), func(start, end int) {
Given what you pointed out (that `Decode` performs subgroup checks anyway) I guess we can remove the explicit subgroup checks and obviate this whole debate.

2025-02-14 17:34 UTC, ivokub commented on backend/groth16/bls12-377/mpcsetup/utils.go
> +	return wp.Submit(len(s), func(start, end int) {
I agree. Imo its the cleanest solution. But leave a comment that in place so that we could remember in the future that the subgroup checks are done elsewhere

2025-02-14 20:27 UTC, Tabaie commented on backend/groth16/bls12-377/mpcsetup/phase2.go
> +	coeffTau1 := lagrangeCoeffsG1(commons.G1.Tau, n)           // [L_{ω⁰}(τ)]₁, [L_{ω¹}(τ)]₁, ... where ω is a primitive sizeᵗʰ root of unity
From the looks of it they're all used in the same loop. Unless we want to iterate over the constraints multiple times?

2025-02-19 11:55 UTC, ivokub approved these changes
Thank you very much @Tabaie for addressing the issues. Sorry for the long back and forth. There are still some performance optimisations and additional features, but I have collected them in https://github.com/Consensys/gnark/issues/1428 for now. See if there is something missing there.

Good to merge from my side.

2025-02-19 11:55 UTC, ivokub commented on backend/groth16/bls12-377/mpcsetup/phase2.go
> +	coeffTau1 := lagrangeCoeffsG1(commons.G1.Tau, n)           // [L_{ω⁰}(τ)]₁, [L_{ω¹}(τ)]₁, ... where ω is a primitive sizeᵗʰ root of unity
Indeed, this would require looping over the constraints several times. But I think this shouldn't be an issue, I'd recon the time-consuming part is the `accumulateG1` and `accumulateG2` parts, not looping the iterator.

But lets postpone, I'm creating a new issue for it.

2025-02-19 15:43 UTC, Tabaie commented
Thank you for the detailed review @ivokub!

2025-02-19 15:44 UTC, merged