refactor: Compile(ecc.ID) -> Compile(field *big.Int)
ConsenSys/gnark pull request #328
Opened 2022-06-06 17:30 UTC by gbotrel

- build: update to latest gnark-crypto
- refactor: frontend.Compile(ecc.ID) -> frontend.Compile(field.Field)
- refactor: field.Field -> *big.Int
- build: update to latest gnark-crypto
- feat: added internal/tinyfield
- refactor: NewWitness(ecc.ID) -> NewWitness(field big.Int)
- feat: build R1CS with tinyfield
- test: ignore range circuit for tinyfield r1cs serialization
- refactor: hint now takes *big.Int scalar field instead of curveID

2022-06-07 14:22 UTC, ivokub requested changes
I think that in general the changes make sense. I'm just thinking that maybe it would be better to name the modulus variable as `primeFieldModulus` etc? If it is `field`, then may be ambiguous?

2022-06-07 14:22 UTC, ivokub commented on internal/generator/backend/main.go
> +			if d.Curve == "tinyfield" {
Maybe instead of manually checking here add field `noBackend` field to `templateData` and check it?

2022-06-07 14:22 UTC, ivokub commented on std/algebra/fields_bls12377/e12_test.go
> +	// TODO @yelhousni restore
Still relevant?

2022-06-07 14:22 UTC, ivokub commented on std/fiat-shamir/transcript_test.go
> +	frSize := len(curveID.ScalarField().Bits()) * 8
Division?

2022-06-07 14:22 UTC, ivokub commented on std/fiat-shamir/transcript_test.go
> +		frSize := len(curveID.ScalarField().Bits()) * 8
Division?

2022-06-07 14:22 UTC, ivokub commented on std/math/bits/conversion_binary.go
> +		NbDigits:             api.Compiler().Field().BitLen(),
If implement `BitLen()` in interface (described in other comment), then can replace.

2022-06-07 14:22 UTC, ivokub commented on std/math/bits/conversion_ternary.go
> +	nbBits := api.Compiler().Field().BitLen()
If implement `BitLen()` in interface (described in other comment), then can replace.

2022-06-07 18:59 UTC, gbotrel commented on internal/utils/field_to_curve.go
> +func FieldToCurve(q *big.Int) ecc.ID {
might be in a very distant future; however this method is internal and here to make this refactor smoother (ie we should kill the Curve() API anyway -- )

2022-06-07 19:00 UTC, gbotrel commented on backend/witness/witness.go
> +	snarkFieldSize := len(w.CurveID.ScalarField().Bits()) * 8
it's the byte size; Bits() on big int returns the words, so len(bits()) == nbWords .

2022-06-07 19:02 UTC, gbotrel commented on frontend/cs/r1cs/builder.go
> +	q *big.Int
Issue is ConstraintSystem doesn't (and shouldn't expose it). Field() method does an allocation since it duplicates the value for safety.

2022-06-07 19:04 UTC, gbotrel commented on backend/witness/witness.go
> +	snarkFieldSize := len(w.CurveID.ScalarField().Bits()) * 8
that being said, it is not 32-bit compatible, will fix.

2022-06-07 19:05 UTC, gbotrel commented on internal/backend/bls12-377/witness/witness.go
> +	n := int64(4)
4 is the size of the uint32 written at the previous line (len(witness))

2022-06-07 19:06 UTC, gbotrel commented on internal/generator/backend/main.go
> +	}
yes dead code from refactoring

2022-06-07 19:06 UTC, gbotrel commented on std/algebra/fields_bls12377/e12_test.go
> +	// TODO @yelhousni restore
yes

2022-06-07 20:06 UTC, merged

2023-06-17 17:12 UTC, drakstik commented
Hey, I know this is a closed issue, but it was not updated in your Go package documentations https://pkg.go.dev/github.com/consensys/gnark#section-readme. Specifically, the first example given of a cubic equation. Would save time for beginners to just add the ecc.BN254.ScalarField() to the example! I had to look around the GitHub for this, which is good practice, but I'd rather save other's time just a little.

Thanks for all the hard work!