Refactor/kzg srs breakup companion
ConsenSys/gnark pull request #632
Opened 2023-04-08 23:48 UTC by Tabaie

Companion to https://github.com/ConsenSys/gnark-crypto/pull/378.
The main idea is that by breaking up the KZG prover and verifier portions (who only have the generator of G1 in common) we get a lighter-weight Plonk verifying key.
In light of this, we will have the option to serialize and deserialize the KZG verifying key as part of the Plonk verifying key. The advantage to this is its obvious convenience. The (less tangible) disadvantage is that it muddies the conceptual separation between data structures that are resulting from a trusted setup (KZG stuff) and those that are merely precomputed (commitments to selectors etc.)

2023-04-11 15:18 UTC, gbotrel requested changes

2023-04-11 20:53 UTC, Tabaie commented on internal/generator/backend/template/zkpschemes/plonk/plonk.setup.go.tmpl
> +	Kzg kzg.VerifyingKey
I felt that when we have `pk.Kzg` and `vk.Kzg` the context makes the type clear.

2023-04-18 14:20 UTC, ThomasPiellard approved these changes

2023-04-21 13:35 UTC, gbotrel approved these changes

2023-04-21 18:09 UTC, merged