Feat/change opening order kzg
ConsenSys/gnark pull request #694
Opened 2023-05-17 13:15 UTC by ThomasPiellard

@Tabaie I just changed the order of the polynomials during the batch opening at zeta in plonk (see in prove.go where `BatchOpenSinglePoint` is called, same in the verifier where `BatchVerifyMultiPoints` is called). It's to be consistant with with the plonk verifier contract

2023-05-17 17:13 UTC, Tabaie requested changes
All good, except that a few lines and a file should be deleted.

2023-05-17 17:13 UTC, Tabaie commented on backend/plonk/bls12-377/verify.go
> +	// claimedValues := proof.BatchedProof.ClaimedValues[7:]
Wanna get rid of these?

2023-05-17 17:13 UTC, Tabaie commented on backend/plonk/bn254/to_delete.go
This one's begging to be deleted 😁

2023-05-23 19:25 UTC, gbotrel commented
@ThomasPiellard fix lines + merge? :)

2023-05-24 17:15 UTC, Tabaie approved these changes

2023-05-24 18:23 UTC, merged